<?xml version="1.0" encoding="utf-8"?><Database Name="HistoryQuest" Class="HistoryQuestDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=VLADPC\SQLEXPRESS;Initial Catalog=HistoryQuest;Integrated Security=True" SettingsObjectName="HistoryQuest.Domain.Properties.Settings" SettingsPropertyName="HistoryQuestConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CheckPoints" Member="CheckPoints">
    <Type Name="CheckPoint">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="gid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="GeoCoordinates" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="InfoFilePath" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="TasksCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OrderId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsBonus" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ParentGID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="AuthorGID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="CheckPoint_CheckPoint" Member="CheckPoints" ThisKey="gid" OtherKey="ParentGID" Type="CheckPoint" />
      <Association Name="CheckPoint_Task" Member="Tasks" ThisKey="gid" OtherKey="CheckPointGID" Type="Task" />
      <Association Name="CheckPoint_CheckPoint" Member="CheckPoint1" ThisKey="ParentGID" OtherKey="gid" Type="CheckPoint" IsForeignKey="true" />
      <Association Name="User_CheckPoint" Member="User" ThisKey="AuthorGID" OtherKey="gid" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="gid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordFormat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PasswordSalt" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="FaceGID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="User_CheckPoint" Member="CheckPoints" ThisKey="gid" OtherKey="AuthorGID" Type="CheckPoint" />
      <Association Name="User_Like" Member="Likes" ThisKey="gid" OtherKey="UserGID" Type="Like" />
      <Association Name="User_Quest" Member="Quests" ThisKey="gid" OtherKey="AuthorGID" Type="Quest" />
      <Association Name="User_Task" Member="Tasks" ThisKey="gid" OtherKey="AuthorGID" Type="Task" />
      <Association Name="User_TasksToTry" Member="TasksToTries" ThisKey="gid" OtherKey="UserGID" Type="TasksToTry" />
      <Association Name="User_Try" Member="Tries" ThisKey="gid" OtherKey="UserGID" Type="Try" />
      <Association Name="User_UsersInRole" Member="UsersInRoles" ThisKey="gid" OtherKey="UserGID" Type="UsersInRole" />
      <Association Name="Face_User" Member="Face" ThisKey="FaceGID" OtherKey="gid" Type="Face" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Comments" Member="Comments">
    <Type Name="Comment">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="gid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="QuestGID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Quest_Comment" Member="Quest" ThisKey="QuestGID" OtherKey="gid" Type="Quest" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Faces" Member="Faces">
    <Type Name="Face">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="gid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MiddleName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TeacherGID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Info" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="IsTeacher" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Face_User" Member="Users" ThisKey="gid" OtherKey="FaceGID" Type="User" />
      <Association Name="Face_Face" Member="Faces" ThisKey="gid" OtherKey="TeacherGID" Type="Face" />
      <Association Name="Face_PupilsToTeachersRequest" Member="PupilsToTeachersRequests" ThisKey="gid" OtherKey="PupilsGID" Type="PupilsToTeachersRequest" />
      <Association Name="Face_PupilsToTeachersRequest1" Member="PupilsToTeachersRequests1" ThisKey="gid" OtherKey="TeacherGID" Type="PupilsToTeachersRequest" />
      <Association Name="Face_Face" Member="Face1" ThisKey="TeacherGID" OtherKey="gid" Type="Face" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Likes" Member="Likes">
    <Type Name="Like">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="gid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserGID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="TaskGID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="User_Like" Member="User" ThisKey="UserGID" OtherKey="gid" Type="User" IsForeignKey="true" />
      <Association Name="Task_Like" Member="Task" ThisKey="TaskGID" OtherKey="gid" Type="Task" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PupilsToTeachersRequests" Member="PupilsToTeachersRequests">
    <Type Name="PupilsToTeachersRequest">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="gid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PupilsGID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="TeacherGID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="Face_PupilsToTeachersRequest" Member="Face" ThisKey="PupilsGID" OtherKey="gid" Type="Face" IsForeignKey="true" />
      <Association Name="Face_PupilsToTeachersRequest1" Member="Face1" ThisKey="TeacherGID" OtherKey="gid" Type="Face" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Quests" Member="Quests">
    <Type Name="Quest">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="gid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="SourceFilePath" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="AuthorGID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="Quest_Comment" Member="Comments" ThisKey="gid" OtherKey="QuestGID" Type="Comment" />
      <Association Name="Quest_Try" Member="Tries" ThisKey="gid" OtherKey="QuestGID" Type="Try" />
      <Association Name="User_Quest" Member="User" ThisKey="AuthorGID" OtherKey="gid" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Roles" Member="Roles">
    <Type Name="Role">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="gid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Role_UsersInRole" Member="UsersInRoles" ThisKey="gid" OtherKey="RoleGID" Type="UsersInRole" />
    </Type>
  </Table>
  <Table Name="dbo.Tasks" Member="Tasks">
    <Type Name="Task">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="gid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="MaxScore" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="TaskTypeGID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="CheckPointGID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="SourceFilePath" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="AuthorGID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="Task_Like" Member="Likes" ThisKey="gid" OtherKey="TaskGID" Type="Like" />
      <Association Name="CheckPoint_Task" Member="CheckPoint" ThisKey="CheckPointGID" OtherKey="gid" Type="CheckPoint" IsForeignKey="true" />
      <Association Name="User_Task" Member="User" ThisKey="AuthorGID" OtherKey="gid" Type="User" IsForeignKey="true" />
      <Association Name="TaskType_Task" Member="TaskType" ThisKey="TaskTypeGID" OtherKey="gid" Type="TaskType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TasksToTries" Member="TasksToTries">
    <Type Name="TasksToTry">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="gid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserGID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="TryGID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="EarnedScore" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ElapsedTime" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="User_TasksToTry" Member="User" ThisKey="UserGID" OtherKey="gid" Type="User" IsForeignKey="true" />
      <Association Name="Try_TasksToTry" Member="Try" ThisKey="TryGID" OtherKey="gid" Type="Try" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TaskTypes" Member="TaskTypes">
    <Type Name="TaskType">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="gid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="TaskType_Task" Member="Tasks" ThisKey="gid" OtherKey="TaskTypeGID" Type="Task" />
    </Type>
  </Table>
  <Table Name="dbo.Tries" Member="Tries">
    <Type Name="Try">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="gid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="QuestGID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserGID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="IsSuccessful" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Try_TasksToTry" Member="TasksToTries" ThisKey="gid" OtherKey="TryGID" Type="TasksToTry" />
      <Association Name="Quest_Try" Member="Quest" ThisKey="QuestGID" OtherKey="gid" Type="Quest" IsForeignKey="true" />
      <Association Name="User_Try" Member="User" ThisKey="UserGID" OtherKey="gid" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UsersInRoles" Member="UsersInRoles">
    <Type Name="UsersInRole">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="gid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserGID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="RoleGID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="Role_UsersInRole" Member="Role" ThisKey="RoleGID" OtherKey="gid" Type="Role" IsForeignKey="true" />
      <Association Name="User_UsersInRole" Member="User" ThisKey="UserGID" OtherKey="gid" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
</Database>